---
- name: Check if a Dynatrace fixpack is provided locally
  local_action: stat path="{{ playbook_dir }}/roles/{{ dynatrace_fixpack_role_name }}/files/{{ dynatrace_fixpack_file_name }}"
  register: dynatrace_fixpack_provided

- name: Fail if a Dynatrace fixpack is not provided locally
  fail: msg="A Dynatrace fixpack is not provided at {{ playbook_dir }}/roles/{{ dynatrace_fixpack_role_name }}/files/{{ dynatrace_fixpack_file_name }}."
  when: not dynatrace_fixpack_provided.stat.exists

- include: linux/install-dependencies-apt.yml
  when: dynatrace_fixpack_provided.stat.exists and ansible_pkg_mgr == "apt"
- include: linux/install-dependencies-yum.yml
  when: dynatrace_fixpack_provided.stat.exists and ansible_pkg_mgr == "yum"

- include: linux/install-dynatrace-fixpack.yml
  when: dynatrace_fixpack_provided.stat.exists

- include: linux/remove-dependencies-apt.yml
  when: dynatrace_fixpack_provided.stat.exists and ansible_pkg_mgr == "apt"
- include: linux/remove-dependencies-yum.yml
  when: dynatrace_fixpack_provided.stat.exists and ansible_pkg_mgr == "yum"
